### ISSUE TITLE
Render variable names instead of empty strings?

### ISSUE THREAD

**Issue by ivanyurchenko1** [StubbleOrg/Stubble#113]
Hello,

This is not an issue but rather a question / feature request. We're using Stubble to render templates, and we don't know for certain which variables might be missing. We want to show user something like {{variable}} instead of an empty space in case the variable is missing, so at least he would be able to report this missing variable to us. Is it possible to configure / implement it in such a way?

Thank you!

**Comment by Romanx** [comment]
Hi there,

It currently not possible to do this. we have the property `ThrowOnDataMiss` on the render settings which rather than silently returning empty it will throw when a value is not found.

This felt like a good compromise to keep Stubble working identical to the mustache spec and allowing the user to have some saftey if they desired it.

**Comment by ivanyurchenko1** [comment]
Thank you for the answer! I used `ThrowOnDataMiss` and added some logging to make sure we find the missing variables.

**Comment by Romanx** [comment]
Good to know this helped you!
