### ISSUE TITLE
Non English character problem for placeholders

### ISSUE THREAD

**Issue by OzanGuclu** [StubbleOrg/Stubble#145]
I'm currently trying to use Stubble,
One of the need I have is to use Turkish "placeholders" (UTF-8 and not ASCII)

            var stubble = new StubbleBuilder().Configure(settings => settings.AddJsonNet()).Build();
            String json = "{ FullName:\"ÖMER FARUK DEMİR\"}";
            var result = JsonConvert.DeserializeObject(json);
            string Msg = stubble.Render("{{FullName}}", result);

rendered string is 

![image](https://github.com/StubbleOrg/Stubble/assets/8940260/d1414608-2310-4dc9-9ba8-5d280397523d)

is this a bug.

**Comment by Romanx** [comment]
Hi there,

I had a quick look at this. It seems to be related to the fact that by the mustache spec we HTML Encode the results of a tag. It seems theres a difference here with how dotnet and the browser encode `Ö`.

You can override the encoding function on the settings using `settings.SetEncodingFunction()` or you can set the specific tag to unescape using `{{{ FullName }}}` (note the tripple {) or `{{ & FullName }}`.

Changing our default html encoding away from the standard dotnet function feels like a bad idea due to unforseen edge cases especially when there are options to override the encoding function yourself or stop encoding for your specific case. 

Hopefully this helps! 👍

**Comment by OzanGuclu** [comment]
thanks for the explanation.
