### ISSUE TITLE
How do I loop over a dictionary?

### ISSUE THREAD

**Issue by rlabrecque** [StubbleOrg/Stubble#35]
Hey there, sorry for the question but I've exhausted all the tests/example code that I could find.

I've got a template that is similar to:

```
{{#Components}}
InComponents
{{#Schemas}}
InSchemas
// Trying to do a lot of different things in here.
{{/Schemas}}
{{/Components}}
```

And my data context is along the lines of:
```
public class MyBase {
		public MyBase();
		public MyComponents Components { get; set; }
}
public class MyComponents {
		public MyComponents();
		public IDictionary<string, MySchema> Schemas { get; set; }
}
public class MySchema {
		public MySchema();
		public string Description { get; set; }
}
```

My usage so far:
```
		MyBase myBase = GetMyBase();

		StubbleVisitorRenderer stubble = new StubbleBuilder().Build();
		using (StreamReader streamReader = new StreamReader(@"template.mustache", Encoding.UTF8)) {
				var output = stubble.Render(streamReader.ReadToEnd(), myBase);
				Debug.WriteLine(output);
			}
```

I was using a different library before that would output the following assuming `myBase.Components.Schemas.Count == 3` :

```
InComponents
InSchemas
InSchemas
InSchemas
```

Stubble only outputs:

```
InComponents
InSchemas
```

I have figured out how to create a section with a specific key in the dictionary via `{{#MyKeyName}}{{Description}}{{/MyKeyName}}`.

Along the same lines, I'd like to get the key name while looping.

**Comment by Romanx** [comment]
Hi @rlabrecque,

What's happening here is that we exclude Dictionaries by default from being able to be enumerated in section tags. The main reason for this is that we're trying to match the idiomatic way that mustache templates are usually written since in javascript objects are effectively dictionaries and you can only loop over arrays of items.

I've got an example here [in this codepen](https://codepen.io/anon/pen/PxqBGg?editors=1010).

This becomes more complicated in the dotnet world since anything can implement IEnumerable and technically be treated as something that can be enumerated over, we've limited this as you found with a IDictionary since it isn't entirely what the majority are likely to expect.

You can bypass this slightly by using GetEnumerator() which will explicity declare that you want to use the enumerator as the section value which will allow to enumerate the KeyValuePairs in the dictionary, this means you can access the keys and values like:
```
{{#Schemas.GetEnumerator}}
key: {{Key}}, value: {{Value}}
{{/Schemas.GetEnumerator}}
```

This won't however give you the IsFirst or IsLast keys you wanted for some of your render logic, this I would say falls into the case of where you're trying to give your template too much logic and you should probably map you data going into the template to format it into a list or array with the values you want from the dictionary in the way that you want it. Something like this should work
```c#
var dict = new Dictionary<string, string>();
var mapped = dict.Select((kvp, idx) => new { Key = kvp.Key, Value = kvp.Value, IsFirst = idx == 0, IsLast = dict.Last().Equals(kvp) });
```

The reason pushing into the context multiple times is not working is that we consider a push as adding a new block scope, much like a section so we search first within that space before going upwards. Adding to the current scope may be something we'd think of adding but we've not seen a use for it yet as contexts are rarely used this way.

Hopefully that makes sense of some of our decisions, please let me know if you need anymore help.

**Comment by rlabrecque** [comment]
How do you solve the json trailing comma without IsFirst/IsLast?

Like
```
{
  a: "",
  b: ""
}
```

This does help a lot, adding to the current scope would be my primary request for sure.

My use case is specifically parsing OpenAPI and generating various other languages from that. So I can't really change the structures, but I've been using AddValueGetter which covers everything except IsFirst/IsLast. Things are going good.

**Comment by Romanx** [comment]
Hi @rlabrecque,

Do you control the objects you're passing into the renderer? If so then you could enrich the data with the IsFirst, IsLast. It's not really something that the renderer would concern itself with. However this does bring to light the fact that you can control almost every part of the value getting and templating process but can't change the enumeration blacklist. I think moving this to be configurable is a good idea.

**Comment by rlabrecque** [comment]
I can't modify the structure passed in, but I do 'own' it before passing it in, the first thing that I tried was creating extension methods, and I was a little disappointed that didn't work, as that's how the previous mustache library I was using functioned. But `AddValueGetter` has actually worked out very well (with the exception of IsFirst/IsLast.)

Being able to change the enumeration blacklist would be useful in general but I don't think I would use it over what I have now. If you were ever going to do any work based on this ticket I think appending to an existing context would be most valuable for my use case.

I'd still probably have my fork, but I'd really like to do this:
```
            else if (value is IDictionary)
            {
                IDictionary dictValue = value as IDictionary;

                bool bIsFirst = true;
                int i = dictValue.Count;
                foreach (DictionaryEntry v in dictValue)
                {
                    renderer.Render(obj, context.Push(new { Name = v.Key, IsFirst = bIsFirst, IsLast = i == 1 });
                    renderer.Render(obj, context.Append(v.Value);
                    bIsFirst = false;
                    --i;
                }
            }
```

**Comment by Romanx** [comment]
In that context your append would add a new entry to the context `Value` however we would have to give it a key which in this case would have to be provided so would be no different to pushing it into the object above.

Extension methods is a complicated one since we're using reflection to discover what methods, properties and fields are available. It's possible we would add a method for registering assemblies to lookup extension methods from but no one has yet asked for it.

Something that may be a possible alternative is the _Helper_ library we're writing which will allow you to add your own tags which will run a registered function so you could have an IsLast/IsFirst helper which would get the current context and allow you to conditionally render the tag body. That's not yet public since i'm working on it sporadically but i'll keep your use case in mind.

**Comment by rlabrecque** [comment]
> In that context your append would add a new entry to the context Value however we would have to give it a key which in this case would have to be provided so would be no different to pushing it into the object above.

Hmm yeah, I'd just want it to "spread" the object at that level, not add the level of indirection.

> Something that may be a possible alternative is the Helper library we're writing which will allow you to add your own tags which will run a registered function so you could have an IsLast/IsFirst helper which would get the current context and allow you to conditionally render the tag body. That's not yet public since i'm working on it sporadically but i'll keep your use case in mind.

Yeah, that sounds fantastic! Really just any cleaner way of doing IsFirst/IsLast or just generally solving the json trailing comma problem would be ideal. I don't mind losing `Name = v.Key` and going back to just `Key`.

Overall though I'm extremely happy with how things have worked out 👍

**Comment by Romanx** [comment]
I'm glad that you're happy with your solution. Let me know if we can integrate any of the things you had to change to perhaps make it easier without adding any complexity. I'll close this for now but try to remember to comment here when i'm done with the helper library 👍

**Comment by Romanx** [comment]
@rlabrecque I've pushed public the work that i've been doing on the Stubble.Helpers library [here](https://github.com/StubbleOrg/Stubble.Helpers) if you'd like to try it. Currently it's not published on nuget but you could manually get the nupkg from appveyor [here.](https://ci.appveyor.com/project/Romanx/stubble-helpers)
