### ISSUE TITLE
Powershell?

### ISSUE THREAD

**Issue by Palloquin** [StubbleOrg/Stubble#39]
Hi all,

_Disclaimer:_ I am not a very versed .net developer.... 

I am looking to use Mustache templates in PowerShell. Would it be doable to use Stubble?

**Comment by Palloquin** [comment]
Okay, I'm still very interested in discussing this topic.

For now I'm building a VS project that will expose PowerShell Cmdlets to interact with Stubble

A first working test got me to this cmdlet:
`Invoke-Stubble -template $template -json $data`

It will do as a basic stubble template merge. It takes a string as template and a string holding JSON. It works.

I program a lot, but this is new terrain for me, also I've never created a GIT repository. I would like to share my project with the world, but wouldn't mind some expert help ;)

**Comment by Palloquin** [comment]
Still very basic, but in case anybody is interested:
https://github.com/Palloquin/PSStubble/

**Comment by Romanx** [comment]
Hey @Palloquin thanks for posting this here for anyone else who may need it. I don't use powershell that much myself but I can definitely see the use. You may want to consider taking a dependency on [Json.Net](https://www.nuget.org/packages/Newtonsoft.Json/) for the json deserialization since deserializing to `Dictionary<string, object>` can make it harder for Stubble to work out your types and your template may not render correctly.

We have [helpers specifically for Json.Net](https://github.com/StubbleOrg/Stubble.Extensions.JsonNet) to help with this issue.

Thanks 👍

**Comment by Romanx** [comment]
If anyone wants to help make this better please look at https://github.com/Palloquin/PSStubble/ and contribute. @Palloquin if this gets some attention i'll add it to our readme. Thanks again.

**Comment by Palloquin** [comment]
> 
> 
> Hey @Palloquin thanks for posting this here for anyone else who may need it. I don't use powershell that much myself but I can definitely see the use. You may want to consider taking a dependency on [Json.Net](https://www.nuget.org/packages/Newtonsoft.Json/) for the json deserialization since deserializing to `Dictionary<string, object>` can make it harder for Stubble to work out your types and your template may not render correctly.
> 
> We have [helpers specifically for Json.Net](https://github.com/StubbleOrg/Stubble.Extensions.JsonNet) to help with this issue.
> 
> Thanks 👍

Hey @Romanx, Thank you for your support and advice. I changed over to using Json.Net!
