### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ipjohnson** [StubbleOrg/Stubble#86]
I'm curious what kind of performance this has compared to something like razor?

**Comment by Romanx** [comment]
Hi there,

Unfortunately its not really an Apples to Apples comparison since Razor does a lot more and spends much more time compiling the template to create an ultra efficient renderer.

We're the fastest mustache renderer (that we've found) and hold up well against other renderers as seen [here.](https://xoofx.com/blog/2017/11/13/implementing-a-text-templating-language-and-engine-for-dotnet/)

If you can compile your template then the compilation would take time however your renderer should be much faster. There are some limitations to this method however.

Hopefully this helps, please let us know if you need anything else.
