### ISSUE TITLE
Newest alpha release not available on Nuget

### ISSUE THREAD

**Issue by peterlazzarino** [StubbleOrg/Stubble#9]
I understand this is kind of a ridiculous request but I am working on an porting an app that used Nustache to .Net core and it seems like your previous version wasn't compatible with the latest version of .Net core. I'm assuming the new alpha will have compatibility so I was wondering when it will be available on Nuget?

Thanks

**Comment by Romanx** [comment]
Hey,

It's not a ridiculous request as we do currently have these on nuget (however the ordering is currently broken in nuget due to me switching to SemVer v2.0 woops). You can find the newest package on nuget here: https://www.nuget.org/packages/Stubble.Core/1.0.0-alpha15

As a warning however, Stubble is still in alpha and i'm making the occasional breaking change in the interfaces. Feel free to use Stubble and report any issues you find, I'll try my best to add migration docs to any releases i make documenting the changes.

**Comment by peterlazzarino** [comment]
Thanks! The new version works great and was a simple port over from Nustache. I'll let you know if we find any issues and will try to contribute as well.
